<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/table_jui.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basepath() . '/js/custom.js')
                                      ->prependFile($this->basepath() . '/js/md5.min.js')
                                      ->prependFile($this->basepath() . '/js/jquery.dataTables.min.js')
                                      ->prependFile($this->basepath() . '/js/jquery.bpopup.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js')
                                      
                                         ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                             <li><a href="<?php echo $this->url('slider') ?>"><?php echo $this->translate('Slider') ?></a></li>
                             <li><a href="<?php echo $this->url('customer') ?>"><?php echo $this->translate('Customer') ?></a></li>
                             </ul>
                        <ul class="nav f-right">
                            <?php if(isset($_SESSION['userLogined'])):?>
                            <li><a href="javascript::void(0);"><?php echo $this->translate('Welcome ') . $_SESSION['userLogined']->userName . "!" ?></a></li>
                            <?php else: ?>
                            <li><a href="javascript::void(0);" id="btn-login"><?php echo $this->translate('Login') ?></a></li>
                            <?php endif?>
                             <li><a href="<?php echo $this->url('register')?>"><?php echo $this->translate('Register') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            
            
            <div class="clear"></div>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <?php echo $this->partial('partials/loginForm.phtml')?>
        
    </body>
</html>
